#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
theme: jekyll-theme-slate
#theme: jekyll-theme-minimal

markdown: redcarpet
redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]

