#markdown: CommonMarkGhPages
#commonmark:
#options: ["UNSAFE", "SMART", "FOOTNOTES"]
#extensions: ["strikethrough", "autolink", "table", "tagfilter"]

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

#plugins:
#  - jekyll-sitemap

#google_analytics:
#theme: jekyll-theme-minimal
theme: jekyll-theme-slate
