title: rfriends3
description: All for Love Radio
show_downloads: false
#github.is_project_page: false
#github.repository_url: https://rfriends.github.io/rfriends/
#github.repository_title: Home
plugins:
  - jekyll-sitemap
google_analytics:
theme: jekyll-theme-slate
